from time import sleep
pessoas = ['Silmara','Silma', 'Walder','Vitor']
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
print('-=' * 10)
sleep(1)
print('Silmara e Vitor não poderão comparecer ao jantar')
sleep(1.5)
pessoas[0] = 'Maria'
pessoas[3] = 'Maitê'
print('Vou convidar Maria e Maitê')
sleep(1.5)
print('-=' * 10)
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
sleep(1)
print('-=' * 10)
print('Encontrei uma mesa de jantar maior')
sleep(1.2)
print('Vou convidar mais três pessoas')
pessoas.insert(3, 'Wanderson')
pessoas.append('Adriana')
pessoas.append('Rosângela')
print('-=' * 10)
sleep(1.5)
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
sleep(0.5)
print('Venha para o jantar',pessoas[4])
sleep(0.5)
print('Venha para o jantar',pessoas[5])
sleep(0.5)
print('Venha para o jantar',pessoas[6])

