from time import sleep
pessoas = ['Silmara','Silma', 'Walder','Vitor']
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
sleep(1)
print('Eu estou convidadando', len(pessoas),'pessoas')
sleep(0.5)
print('-=' * 10)
sleep(1.5)
print('Silmara e Vitor não poderão comparecer ao jantar')
sleep(1.5)
pessoas[0] = 'Maria'
pessoas[3] = 'Maitê'
print('Vou convidar Maria e Maitê')
sleep(1.5)
print('-=' * 10)
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
sleep(1)
print('Eu estou convidadando', len(pessoas),'pessoas')
sleep(1.5)
print('-=' * 10)
print('Encontrei uma mesa de jantar maior')
sleep(1.2)
print('Vou convidar mais três pessoas')
pessoas.insert(3, 'Wanderson')
pessoas.append('Adriana')
pessoas.append('Rosângela')
print('-=' * 10)
sleep(1.5)
print('Venha para o jantar',pessoas[0])
sleep(0.5)
print('Venha para o jantar',pessoas[1])
sleep(0.5)
print('Venha para o jantar',pessoas[2])
sleep(0.5)
print('Venha para o jantar',pessoas[3])
sleep(0.5)
print('Venha para o jantar',pessoas[4])
sleep(0.5)
print('Venha para o jantar',pessoas[5])
sleep(0.5)
print('Venha para o jantar',pessoas[6])
sleep(1)
print('Eu estou convidadando', len(pessoas),'pessoas')
sleep(2)
print('-=' * 10)
print('Oh não, a mesa de jantar não chegará a tempo')
sleep(1.5)
print('Vai ter espaço para somente dois convidados')
sleep(1.5)
print('-=' * 10)
pessoas.pop()
print('Desculpe, não irei mais te convidar Rosângela')
sleep(1.5)
pessoas.pop()
print('Desculpe, não irei mais te convidar Adriana')
sleep(1.5)
pessoas.remove('Walder')
print('Desculpe, não irei mais te convidar Walder')
sleep(1.5)
print('Desculpe, não irei mais te convidar', pessoas[1])
del pessoas[1]
sleep(1.5)
print('Desculpe, não irei mais te convidar', pessoas[1])
del pessoas[1]
print('-=' * 10)
sleep(2)
print('Os convidados serão', pessoas)
sleep(1)
print('Eu estou convidadando', len(pessoas),'pessoas')
sleep(1.5)
print('-=' * 10)
sleep(2)
print('A festa terminou...')
sleep(1.5)
del pessoas[0]
del pessoas[0]
print('Agora há', len(pessoas),'pessoas na festa.')